2025-09-02 14:13:16

diff --git a/grep_data_rate b/grep_data_rate
--- a/grep_data_rate
+++ b/grep_data_rate
@@ -162,17 +162,17 @@ for molecule in ${molecules[@]}; do
         else
             Energy_Gap=0.0000000000
         fi
+
+        Fluorescence_rate=$(ORCA-Grepk -q "$FLUO.out")
         
-        # Fluorescence_rate=$(ORCA-Grepk -q "$FLUO.out")
-        
-        # ISC_rate_1=$(ORCA-Grepk -q "$ISC_1.out")
-        # ISC_rate_2=$(ORCA-Grepk -q "$ISC_2.out")
-        # ISC_rate_3=$(ORCA-Grepk -q "$ISC_3.out")
+        ISC_rate_1=$(ORCA-Grepk -q "$ISC_1.out")
+        ISC_rate_2=$(ORCA-Grepk -q "$ISC_2.out")
+        ISC_rate_3=$(ORCA-Grepk -q "$ISC_3.out")
 
 
-        # RISC_rate_1=$(ORCA-Grepk -q "$RISC_1.out")
-        # RISC_rate_2=$(ORCA-Grepk -q "$RISC_2.out")
-        # RISC_rate_3=$(ORCA-Grepk -q "$RISC_3.out")
+        RISC_rate_1=$(ORCA-Grepk -q "$RISC_1.out")
+        RISC_rate_2=$(ORCA-Grepk -q "$RISC_2.out")
+        RISC_rate_3=$(ORCA-Grepk -q "$RISC_3.out")
 
         # ST=$(grep 'DELE' $ISC_1.out | awk '{print $4}')
         # echo "ISC rate 1: $ISC_rate_1"
@@ -182,21 +182,22 @@ for molecule in ${molecules[@]}; do
 
 
         # Make sure 1 and 3 are equal if one of them is zero
-        # if [ -z $ISC_rate_3 ] && [ "$ISC_rate_1" != "0.00000000e+00" ]; then
-        #     ISC_rate_3=$ISC_rate_1
-        #     # echo "Replaced ISC rate 3 with ISC rate 1"
-        # elif [ -z $ISC_rate_1 ] && [ "$ISC_rate_3" != "0.00000000e+00" ]; then
-        #     ISC_rate_1=$ISC_rate_3
-        # fi
+        if [ -z $ISC_rate_3 ] && [ "$ISC_rate_1" != "0.00000000e+00" ]; then
+            ISC_rate_3=$ISC_rate_1
+            # echo "Replaced ISC rate 3 with ISC rate 1"
+        elif [ -z $ISC_rate_1 ] && [ "$ISC_rate_3" != "0.00000000e+00" ]; then
+            ISC_rate_1=$ISC_rate_3
+        fi
 
-        # if [ -z $RISC_rate_3 ] && [ "$RISC_rate_1" != "0.00000000e+00" ]; then
-        #     RISC_rate_3=$RISC_rate_1
-        #     # echo "Replaced RISC rate 3 with RISC rate 1"
-        # elif [ -z $RISC_rate_1 ] && [ "$RISC_rate_3" != "0.00000000e+00" ]; then
-        #     RISC_rate_1=$RISC_rate_3
-        # fi
-        # ISC_sum=$(printf "%.10g + %.10g + %.10g\n" "$ISC_rate_1" "$ISC_rate_2" "$ISC_rate_3" | bc -l 2>/dev/null)
-        # RISC_sum=$(printf "%.10g + %.10g + %.10g\n" "$RISC_rate_1" "$RISC_rate_2" "$RISC_rate_3" | bc -l 2>/dev/null)
+        if [ -z $RISC_rate_3 ] && [ "$RISC_rate_1" != "0.00000000e+00" ]; then
+            RISC_rate_3=$RISC_rate_1
+            # echo "Replaced RISC rate 3 with RISC rate 1"
+        elif [ -z $RISC_rate_1 ] && [ "$RISC_rate_3" != "0.00000000e+00" ]; then
+            RISC_rate_1=$RISC_rate_3
+        fi
+
+        ISC_sum=$(printf "%.10g + %.10g + %.10g\n" "$ISC_rate_1" "$ISC_rate_2" "$ISC_rate_3" | bc -l 2>/dev/null)
+        RISC_sum=$(printf "%.10g + %.10g + %.10g\n" "$RISC_rate_1" "$RISC_rate_2" "$RISC_rate_3" | bc -l 2>/dev/null)
         # echo "ISC 1: $ISC_rate_1"
         # echo "ISC 2: $ISC_rate_2"
         # echo "ISC 3: $ISC_rate_3"
@@ -205,37 +206,37 @@ for molecule in ${molecules[@]}; do
         # echo "RISC 2: $RISC_rate_2"
         # echo "RISC 3: $RISC_rate_3"
         # echo "RISC sum: $RISC_sum"
-        # if [ "$ISC_sum" != "0.00000000e+00" ]; then
-        #     if (( $(echo "$ISC_sum < 0" | bc -l) )); then
-        #         # echo "Negative ISC rate for $molecule with $functional"
-        #         ISC_average="NaN"
-        #     else
-        #         ISC_average=$(printf "%.10g / 3\n" "$ISC_sum" | bc -l 2>/dev/null)
-        #         # echo "ISC average: $ISC_average"
-        #     fi
-        # else
-        #     ISC_average=0.0000000000
-        # fi
+        if [ "$ISC_sum" != "0.00000000e+00" ]; then
+            if (( $(echo "$ISC_sum < 0" | bc -l) )); then
+                # echo "Negative ISC rate for $molecule with $functional"
+                ISC_average="NaN"
+            else
+                ISC_average=$(printf "%.10g / 3\n" "$ISC_sum" | bc -l 2>/dev/null)
+                # echo "ISC average: $ISC_average"
+            fi
+        else
+            ISC_average=0.0000000000
+        fi
 
-        # if [ "$RISC_sum" != "0.00000000e+00" ]; then
-        #     if (( $(echo "$RISC_sum < 0" | bc -l) )); then
-        #         # echo "Negative RISC rate for $molecule with $functional"
-        #         RISC_average="NaN"
-        #     else
-        #         RISC_average=$(printf "%.10g / 3\n" "$RISC_sum" | bc -l 2>/dev/null)
-        #         # echo "RISC average: $RISC_average"
-        #     fi
-        # else
-        #     RISC_average=0.0000000000
-        # fi
+        if [ "$RISC_sum" != "0.00000000e+00" ]; then
+            if (( $(echo "$RISC_sum < 0" | bc -l) )); then
+                # echo "Negative RISC rate for $molecule with $functional"
+                RISC_average="NaN"
+            else
+                RISC_average=$(printf "%.10g / 3\n" "$RISC_sum" | bc -l 2>/dev/null)
+                # echo "RISC average: $RISC_average"
+            fi
+        else
+            RISC_average=0.0000000000
+        fi
 
-        # if [ -f "$FLUO.spectrum" ]; then
-        #     emission=$(ORCA-GrepSpectrum "$FLUO.spectrum")
-        #     emission_wave=$(echo "$emission" | awk '{printf "%.2f\n", 1e7/$1}')
-        # else
-        #     echo "$FLUO.spectrum not found"
-        #     emission_wave=0.00
-        # fi
+        if [ -f "$FLUO.spectrum" ]; then
+            emission=$(ORCA-GrepSpectrum "$FLUO.spectrum")
+            emission_wave=$(echo "$emission" | awk '{printf "%.2f\n", 1e7/$1}')
+        else
+            echo "$FLUO.spectrum not found"
+            emission_wave=0.00
+        fi
         # # multiwfn_ana $FLUO s1
         # # echo "RUNNING: multiwfn_ana $FLUO s1"
 
@@ -312,7 +313,7 @@ for molecule in ${molecules[@]}; do
         read -r x_r x_i y_r y_i z_r z_i <<<$(echo "$SOCME" | tr ',' ' ')
         # Extract Re_SOCME components
         read -r x y z <<<$(grep "CALCULATED REDUCED SOCME BETWEEN TRIPLETS AND SINGLETS" -A 7 "$zeff.out" | grep "0        1" | awk '{print $3, $4, $5}')  
-             
+
         totSOCME=$(awk -v xr="$x_r" -v xi="$x_i" -v yr="$y_r" -v yi="$y_i" -v zr="$z_r" -v zi="$z_i" \
         'BEGIN {
             x2 = xr*xr + xi*xi;
@@ -366,33 +367,33 @@ for molecule in ${molecules[@]}; do
             fi
         fi
 
-        # if [ "$Fluorescence_rate" == "0.00000000e+00" ]; then
-        #     if ! qjlist | grep -q "$FLUO"; then
-        #         echo "$FLUO"
-        #     fi
-        # fi
+        if [ "$Fluorescence_rate" == "0.00000000e+00" ]; then
+            if ! qjlist | grep -q "$FLUO"; then
+                echo "$FLUO"
+            fi
+        fi
 
-        # if [ "$ISC_rate_1" == "0.00000000e+00" ]; then
-        #     echo "$ISC_1"
-        # fi
-        # if [ "$ISC_rate_2" == "0.00000000e+00" ]; then
-        #     echo "$ISC_2"
-        # fi
-        # if [ "$ISC_rate_3" == "0.00000000e+00" ]; then
-        #     echo "$ISC_3"
-        # fi
+        if [ "$ISC_rate_1" == "0.00000000e+00" ]; then
+            echo "$ISC_1"
+        fi
+        if [ "$ISC_rate_2" == "0.00000000e+00" ]; then
+            echo "$ISC_2"
+        fi
+        if [ "$ISC_rate_3" == "0.00000000e+00" ]; then
+            echo "$ISC_3"
+        fi
 
-        # if [ "$RISC_rate_1" == "0.00000000e+00" ]; then
-        #     echo "$RISC_1"
-        # fi
+        if [ "$RISC_rate_1" == "0.00000000e+00" ]; then
+            echo "$RISC_1"
+        fi
 
-        # if [ "$RISC_rate_2" == "0.00000000e+00" ]; then
-        #     echo "$RISC_2"
-        # fi
+        if [ "$RISC_rate_2" == "0.00000000e+00" ]; then
+            echo "$RISC_2"
+        fi
 
-        # if [ "$RISC_rate_3" == "0.00000000e+00" ]; then
-        #     echo "$RISC_3"
-        # fi
+        if [ "$RISC_rate_3" == "0.00000000e+00" ]; then
+            echo "$RISC_3"
+        fi
 
         # echo "writing to $output"
 
