2025-07-24 14:56:31

diff --git a/grep_data_risc b/grep_data_risc
--- a/grep_data_risc
+++ b/grep_data_risc
@@ -154,7 +154,7 @@ for molecule in $molecules; do
         Hab_from=$(ORCA-chkOrbital -q "$Hab.out" | awk '{print $1}')
         Hab_to=$(ORCA-chkOrbital -q "$Hab.out" | awk '{print $1}')
         Hab_excit=$(( $Hab_to - $Hab_from ))
-        if [ $Hab_excit -eq 1 ]; then
+        # if [ $Hab_excit -eq 1 ]; then
             if [ ! -z "$E_Hab" ]; then
                 echo "Running:: MarcusCTRate $E_ES $E_Hab $E_TS $lamda"
                 MarcusCTRate $E_ES $E_Hab $E_TS $lamda
@@ -162,10 +162,10 @@ for molecule in $molecules; do
             else
                 MarcusRate="NaN"
             fi
-        else
-            MarcusRate="NaN"
-            echo "Error: $Hab excitation is from $Hab_from to $Hab_to" >&2
-        fi
+        # else
+        #     MarcusRate="NaN"
+        #     echo "Error: $Hab excitation is from $Hab_from to $Hab_to" >&2
+        # fi
         # Debugging: Print the values of the variables
         # echo "Debug: molecule=$molecule, functional=$functional, SPE_S0=$SPE_S0, SPE_S1=$SPE_S1, SPE_T1=$SPE_T1, Energy_Gap=$Energy_Gap, Fluorescence_rate=$Fluorescence_rate, RISC_rate_1=$RISC_rate_1, RISC_rate_2=$RISC_rate_2, RISC_rate_3=$RISC_rate_3, RISC_average=$RISC_average, RISC_rate_1=$RISC_rate_1, RISC_rate_2=$RISC_rate_2, RISC_rate_3=$RISC_rate_3, RISC_average=$RISC_average, DIndex_S1=$DIndex_S1, XYZ_S1_S0=$XYZ_S1_S0, XYZ_T1_S0=$XYZ_T1_S0, XYZ_T1_S1=$XYZ_T1_S1, ref=$ref"
         #        "Molecule_Name,Functional,RISC_Rate,npoints1,npoints2,K_Vector_sum,lamda_sum(cm-1),lamda_max_freq,lamda_maxmode_socme,HR_max_freq,HR_max_mode,HR_maxmode_socme1,HR_maxmode_socme2,rmsd_s1_t1,ref_socme1,ref_socme2"
