2024-12-16 15:34:11

diff --git a/multiwfn_ana b/multiwfn_ana
--- a/multiwfn_ana
+++ b/multiwfn_ana
@@ -1,5 +1,5 @@
 #!/bin/bash
-set -e  # Exit immediately if a command exits with a non-zero status
+# set -e  # Exit immediately if a command exits with a non-zero status
 input=${1%.*}
 if [ ! -f $input.gbw ]; then
     echo "Error: $input.gbw not found"
