2024-12-16 20:19:02

diff --git a/ORCA-GrepVC b/ORCA-GrepVC
--- a/ORCA-GrepVC
+++ b/ORCA-GrepVC
@@ -12,9 +12,29 @@ for file in "$@"; do
       continue
   fi
 
+  if ! grep -q "will need at least" $input.out; then
+      echo "Error: 'number of modes' not found in $input.out"
+      continue
+  fi
+
+  if ! grep -q "The Huang-Rhys factor per mode is:" $input.out; then
+      echo "Error: 'The Huang-Rhys factor per mode is:' not found in $input.out"
+      continue
+  fi
+
+  if ! grep -q "The K vector (a.u.) is:" $input.out; then
+      echo "Error: 'The K vector (a.u.) is:' not found in $input.out"
+      continue
+  fi
+
+  if ! grep -q "The reorganization energy per mode is:" $input.out; then
+      echo "Error: 'The reorganization energy per mode is:' not found in $input.out"
+      continue
+  fi
+
   nmode=$(grep "will need at least" $input.out | awk '{print $5}')
-  # grep -A $((nmode + 5)) "The Huang-Rhys factor per mode is:" $input.out | tail -n +6 # > $file_HR
-  grep -A $((nmode + 5)) "The K vector (a.u.) is:" $input.out | tail -n +6 # > $file_K
-  grep -A $((nmode + 5)) "The reorganization energy per mode is:" $input.out | tail -n +6 # > $file_lamda
+  grep -A $((nmode + 5)) "The Huang-Rhys factor per mode is:" $input.out | tail -n +6  > $file_HR
+  grep -A $((nmode + 5)) "The K vector (a.u.) is:" $input.out | tail -n +6  > $file_K
+  grep -A $((nmode + 5)) "The reorganization energy per mode is:" $input.out | tail -n +6  > $file_lamda
 
 done
