2025-09-03 14:19:32

diff --git a/template_orca_default_hpc b/template_orca_default_hpc
--- a/template_orca_default_hpc
+++ b/template_orca_default_hpc
@@ -77,7 +77,7 @@ finish=0
 if [ -f $tdir/${input%.inp}.out ]; then
   finish=$(grep "****ORCA TERMINATED NORMALLY****" $tdir/${input%.inp}.out | wc -l)
   echo "ORCA calculation is finished successfully."
- else 
+else 
   echo "$tdir/${input%.inp}.out is missing, exit..."
   exit 99
 fi
@@ -92,97 +92,98 @@ fi
 
 i=0
 
-i=0
-while [ $finish -eq 0 ]; do
-  i=$((i+1))
-  echo "Checking round $i"
-  ORCA-chkOrbital  ${input%.inp}.out
-  echo "ORCA calculation returned with error, restart the calculation..."
-# Back up for previous run
-  cp $tdir/${input%.inp}.out $tdir/${input%.inp}.o$i
-  cp $tdir/${input%.inp}.gbw $tdir/${input%.inp}.g$i
-  cp $tdir/${input%.inp}.gbw $tdir/$orbital
-# Redo the calculation
-  $ORCA_ROOT/orca  $input > ${input%.inp}.out 2> ${input%.inp}.err 
-# Check finish status again
-  # finish=$(grep -c "****ORCA TERMINATED NORMALLY****" $tdir/${input%.inp}.out)
-  # if [ $finish -eq 1 ]; then
-  #   echo "ORCA calculation is finished successfully."
-  #   break
-  # fi  
-  orb_from=$( ORCA-chkOrbital -q "${input%.inp}.out" | awk '{print $1}' 2> /dev/null)
-  orb_to=$( ORCA-chkOrbital -q " ${input%.inp}.out" | awk '{print $3}' 2> /dev/null)
-  finish=$(($orb_to - $orb_from))
-  if [ $finish -ne 1 ]; then
-    finish=0  
-  fi
+if [ $(grep XYZFILE $tdir/$input | awk '{print $4}' ) -eq 1 ]; then
+  i=0
+  while [ $finish -eq 0 ]; do
+    i=$((i+1))
+    echo "Checking round $i"
+    ORCA-chkOrbital  ${input%.inp}.out
+    echo "ORCA calculation returned with error, restart the calculation..."
+  # Back up for previous run
+    cp $tdir/${input%.inp}.out $tdir/${input%.inp}.o$i
+    cp $tdir/${input%.inp}.gbw $tdir/${input%.inp}.g$i
+    cp $tdir/${input%.inp}.gbw $tdir/$orbital
+  # Redo the calculation
+    $ORCA_ROOT/orca  $input > ${input%.inp}.out 2> ${input%.inp}.err 
+  # Check finish status again
+    # finish=$(grep -c "****ORCA TERMINATED NORMALLY****" $tdir/${input%.inp}.out)
+    # if [ $finish -eq 1 ]; then
+    #   echo "ORCA calculation is finished successfully."
+    #   break
+    # fi  
+    orb_from=$( ORCA-chkOrbital -q "${input%.inp}.out" | awk '{print $1}' 2> /dev/null)
+    orb_to=$( ORCA-chkOrbital -q " ${input%.inp}.out" | awk '{print $3}' 2> /dev/null)
+    finish=$(($orb_to - $orb_from))
+    if [ $finish -ne 1 ]; then
+      finish=0  
+    fi
 
-   if [ $i -eq 5 ]; then
-    echo "Iteration hits the limit to $i, quitting... "
-    if [ -f  $tdir/${input%.inp}.out  ] ; then  cp $tdir/${input%.inp}.out   $CurrDir/  ; fi ;
-     if [ -f  $tdir/${input%.inp}.err  ] ; then  cp $tdir/${input%.inp}.err   $CurrDir/  ; fi ; 
-    exit 88
-  fi 
-done 
-
-if [ $(grep "freq" $tdir/${input%.inp}.inp | wc -l) -eq 1 ]; then
-  hess=0
-  echo "Checking imaginary mode... "
-  freq=`grep "vibrational_frequencies" -A 8 ${input%.inp}.hess | tail -n 1 | awk '{print $2}'`
-  if [[ "$freq" == -* ]]; then
-    echo "Vibrational mode 6 is an imaginary mode."
-    echo "Frequency 6: $freq"
-    hess=1
-  else
-    echo "Frequency 6: $freq"
-    echo "No imaginary mode found. Exiting..."
-    hess=0
-  fi
+    if [ $i -eq 5 ]; then
+      echo "Iteration hits the limit to $i, quitting... "
+      if [ -f  $tdir/${input%.inp}.out  ] ; then  cp $tdir/${input%.inp}.out   $CurrDir/  ; fi ;
+      if [ -f  $tdir/${input%.inp}.err  ] ; then  cp $tdir/${input%.inp}.err   $CurrDir/  ; fi ; 
+      exit 88
+    fi 
+  done 
 fi
+# if [ $(grep "freq" $tdir/${input%.inp}.inp | wc -l) -eq 1 ]; then
+#   hess=0
+#   echo "Checking imaginary mode... "
+#   freq=`grep "vibrational_frequencies" -A 8 ${input%.inp}.hess | tail -n 1 | awk '{print $2}'`
+#   if [[ "$freq" == -* ]]; then
+#     echo "Vibrational mode 6 is an imaginary mode."
+#     echo "Frequency 6: $freq"
+#     hess=1
+#   else
+#     echo "Frequency 6: $freq"
+#     echo "No imaginary mode found. Exiting..."
+#     hess=0
+#   fi
+# fi
 
-h=0
-while [ $hess -eq 1 ]; do
+# h=0
+# while [ $hess -eq 1 ]; do
 
-  cp -f $XYZFILE ${input%.inp}.xyz.i$h
-  echo "${input%.inp}.xyz.i$h is backed up."
-  cp -f ${input%.inp}.out ${input%.inp}.out.i$h
-  echo "${input%.inp}.out.i$h is backed up."
+#   cp -f $XYZFILE ${input%.inp}.xyz.i$h
+#   echo "${input%.inp}.xyz.i$h is backed up."
+#   cp -f ${input%.inp}.out ${input%.inp}.out.i$h
+#   echo "${input%.inp}.out.i$h is backed up."
 
-  $HOME/bin/ORCA/ORCA-displacement $input
+#   $HOME/bin/ORCA/ORCA-displacement $input
 
-  cat ${input%.inp}_v006.xyz > $XYZFILE
+#   cat ${input%.inp}_v006.xyz > $XYZFILE
 
-  sed -i "s/$XYZFILE/${input%.inp}_v006.xyz/" $input
-  echo "Replacing xyz file and restart the calculation..."
+#   sed -i "s/$XYZFILE/${input%.inp}_v006.xyz/" $input
+#   echo "Replacing xyz file and restart the calculation..."
 
-  # actual execution
-  $ORCA_ROOT/orca  $input > ${input%.inp}.out 2> ${input%.inp}.err 
+#   # actual execution
+#   $ORCA_ROOT/orca  $input > ${input%.inp}.out 2> ${input%.inp}.err 
   
-  echo "Orca run for iteration: $h is finished. "
-  echo "Checking imaginary mode again. Iteration: $h "
+#   echo "Orca run for iteration: $h is finished. "
+#   echo "Checking imaginary mode again. Iteration: $h "
 
-  freq=`grep "vibrational_frequencies" -A 8 ${input%.inp}.hess | tail -n 1 | awk '{print $2}'`
+#   freq=`grep "vibrational_frequencies" -A 8 ${input%.inp}.hess | tail -n 1 | awk '{print $2}'`
 
-  if [[ "$freq" == -* ]]; then
-    echo "Vibrational mode 6 is an imaginary mode."
-    echo "Frequency 6: $freq"
-    hess=1
-  else
-    echo "Frequency 6: $freq"
-    echo "No imaginary mode found. Exiting..."
-    break
-  fi 
-  if [ $h -eq 0 ]; then
-    echo "Iteration hits the limit to $h, quitting... "
-    if [ -f  $tdir/${input%.inp}.out  ] ; then  cp $tdir/${input%.inp}.out   $CurrDir/  ; fi ;
-    if [ -f  $tdir/${input%.inp}.err  ] ; then  cp $tdir/${input%.inp}.err   $CurrDir/  ; fi ; 
-   if [ -f  $tdir/${input%.inp}.hess ] ; then  cp $tdir/${input%.inp}.hess  $CurrDir/  ; fi ; 
-   if [ -f  $tdir/${input%.inp}.gbw  ] ; then  cp $tdir/${input%.inp}.gbw   $CurrDir/  ; fi ;
-   if [ -f  $tdir/${input%.inp}.xyz  ] ; then  cp $tdir/${input%.inp}.xyz   $CurrDir/  ; fi ;
-    exit 77
-  fi 
-  h=$((h+1))
-done
+#   if [[ "$freq" == -* ]]; then
+#     echo "Vibrational mode 6 is an imaginary mode."
+#     echo "Frequency 6: $freq"
+#     hess=1
+#   else
+#     echo "Frequency 6: $freq"
+#     echo "No imaginary mode found. Exiting..."
+#     break
+#   fi 
+#   if [ $h -eq 0 ]; then
+#     echo "Iteration hits the limit to $h, quitting... "
+#     if [ -f  $tdir/${input%.inp}.out  ] ; then  cp $tdir/${input%.inp}.out   $CurrDir/  ; fi ;
+#     if [ -f  $tdir/${input%.inp}.err  ] ; then  cp $tdir/${input%.inp}.err   $CurrDir/  ; fi ; 
+#    if [ -f  $tdir/${input%.inp}.hess ] ; then  cp $tdir/${input%.inp}.hess  $CurrDir/  ; fi ; 
+#    if [ -f  $tdir/${input%.inp}.gbw  ] ; then  cp $tdir/${input%.inp}.gbw   $CurrDir/  ; fi ;
+#    if [ -f  $tdir/${input%.inp}.xyz  ] ; then  cp $tdir/${input%.inp}.xyz   $CurrDir/  ; fi ;
+#     exit 77
+#   fi 
+#   h=$((h+1))
+# done
 
 
 
